# Jekyll Configuration for AACR 2025 Dashboard
title: "AACR 2025 Clinical Trial Results Dashboard"
description: "Interactive dashboard visualizing objective response rates from clinical trials reported at AACR 2025"
baseurl: "/aacr2025"
url: "https://inventcures.github.io"

# Google Analytics - replace with your GA4 measurement ID
google_analytics: "G-YQXJ75PNDQ"

# GitHub repository info for visitor tracking
github:
  owner_name: "inventcures"
  repository_name: "inventcures.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude files from build
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE

# Collection settings
collections:
  abstracts:
    output: true
    permalink: /:collection/:name/

# Default settings
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "abstracts"
    values:
      layout: "abstract"